FROM alpine:latest
MAINTAINER Burgy Benjamin <https://twitter.com/minidfx>
# Documentation: https://launchpadlibrarian.net/268329806/How-to-build-toolchain.pdf

# Pebble versions
ENV SDKVER 4.0.1
ENV TOOLVER v4.4.1

# install pre depends
RUN apk add --no-cache -U curl git

# install lang depends
RUN apk add python python-dev
RUN curl -s https://bootstrap.pypa.io/get-pip.py | python -

# install freetype
RUN apk add --no-cache -U freetype-dev

# Install GCC
ENV USE_LTO=no
WORKDIR /home/pebble
RUN apk --no-cache -U add gcc make libc-dev libgcc g++ gnupg flex bison gperf \
zip curl libx11-dev build-base openssl bash m4 flex
RUN apk --no-cache -U add python ruby ruby-rake
RUN curl -OJL https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q2-update/+download/gcc-arm-none-eabi-5_4-2016q2-20160622-src.tar.bz2
RUN mkdir -p ~/toolchain && \
tar -xjf gcc-arm-none-eabi-5_4-2016q2-20160622-linux.tar.bz2 ~/toolchain
WORKDIR /home/pebble/toolchain
RUN cd gcc-arm-none-eabi-5_4-2016q2-20160622-linux/src && \
find -name '*.tar.*' | xargs -I% tar -xf % && \
cd ~/toolchain && \
./build-prerequisites.sh --skip_steps=mingw32 && \
./build-toolchain.sh --skip_steps=mingw32,manual

# install NPM
RUN apk --no-cache -U add nodejs

# install sudo
RUN apk --no-cache -U add sudo

# Create the Pebble user
RUN adduser -D -g "" -G users pebble && \
    mkdir -p /home/pebble/.pebble-sdk && \
    mkdir -p /home/pebble/project

# Install the Pebble Tool
RUN git clone -b $TOOLVER https://github.com/pebble/pebble-tool.git /home/pebble/tool
RUN chown -R pebble:users /home/pebble

# Install the tool dependencies
WORKDIR /home/pebble/tool
RUN pip install -r requirements.txt virtualenv
RUN sudo -u pebble virtualenv --no-site-packages .env && \
source .env/bin/activate && \
pip install -r requirements.txt && \
deactivate
RUN rm -r /root/.cache
RUN chown -R pebble:users /home/pebble

# Prepare the Pebble SDK installation
WORKDIR /home/pebble/.pebble-sdk
RUN sudo -u pebble touch ENABLE_ANALYTICS

# Install the SDK
WORKDIR /home/pebble/tool
RUN yes | sudo -EH -u pebble /usr/bin/python pebble.py sdk install $SDKVER
RUN rm -r /home/pebble/.cache

# Remove SUDO package
RUN apk del --purge sudo

#USER pebble

WORKDIR /home/pebble/project
VOLUME  /home/pebble/project

#ENTRYPOINT ["/usr/bin/python", "/home/pebble/tool/pebble.py"]

#CMD ["--help"]
